---
title: "<span style='font-size: 49pt;'>Forecasting Election Swings in Multiparty Systems Using Underlying Potential for Growth of Parties</span>"
author: "<table style='margin-top: -290px; width: 100%; text-align: center;'><tr><td style='vertical-align: top; padding-right: 5px;'>Hubert Cadieux<br>Sarah-Jane Vincent<br>Camille Pelletier</td><td style='vertical-align: top;'>Catherine Ouellet<br>Jérémy Gilbert<br>Yannick Dufresne</td></tr></table>"
format:
  revealjs:
    theme: dark
    fontsize: 31pt
  pdf:
    fontsize: 31pt
editor: source
---

# [Theoretical Background]{style="font-size: 85pt;"}
[Potential for Growth: What Is It?]{style="font-size: 55pt;"}

```{=html}
<!-- Hi I'm Hubert Cadieux blabla I'm presenting the article I'm writing with blabla: titre 
This article forms part of a collective effort to theorize, conceptualize, and operationalize the concept of a continuous potential for growth and vote solidity by developing new measures of vote intention that capture its dynamic nature in multiparty systems.
I will be conducting my master's thesis on this concept with the goal of mapping respondents' issue attitudes onto this concept.
-->
```

## Traditional Way of Estimating Parties' Chances of Winning

-   In a riding or at the national level <!-- Ici, faire un exemple fictif d'une circonscription avec trois partis A, B et C

        Exemple 1.1:
        Graphique classique de Qc125.
        A a 45% +- 8
        B a 35% +- 8
        C a 20% +- 5
        Conclusions à la lecture du graphique?
        A a une excellente avance, mais pourrait peut-être être challengé par B.
        C a aucune chance de l'emporter.

        Exemple 1.2, MÊMES DONNÉES:
        A a beaucoup de votes fragiles et pas de potentiel de croissance
        B a un vote solide mais pas de potentiel de croissance
        C a une petite base mais solide et un gros potentiel de croissance
        Nouvelles conclusions?
        A a une bonne avance sur B, mais au niveau individuel peut facilement perdre des électeurs à C.
        B a une 2e place facile, mais impossible d'aller plus loin. Espère une séparation des votes entre A et C.
        C est loin en arrière, mais a un potentiel d'aller chercher des électeurs fragiles de A. C a donc + de chances de gagner que B.

        Exemple 1.3 MÊMES DONNÉES mais en simulant une attaque réussie de C sur les segments fragiles de A
        Nouveau graphique classique de Qc125 + graphique de potentiel de croissance

        Conclusions:

        L'opérationnalisation du potentiel de croissance permettrait de forecaster, anticiper des swings potentiels comme à l'exemple 1.3 que les méthodes traditionnelles d'intention de vote ne permettent pas. C'est la logique derrière ce qui nous intéresse dans ce concept.
        
      Deux concepts distincts: solidité du vote et potentiel de croissance

        -->

## Why Study It?

-   More nuanced interpretation of agregated vote intentions
-   Better allocation of parties' resources
-   Identifying parties' room to maneuver
-   Identifying parties' fragile segments of electorate
-   Improving electoral forecasting
-   Better anticipation of electoral swings

## [Research Question]{style="font-size: 85pt;"}

[Can the forecast of ]{style="font-size: 47pt;"} [***electoral swings***]{style="font-size: 55pt; color: #00BFFF;"} [be improved by quantifying a]{style="font-size: 47pt;"} [***party's potential for growth***]{style="font-size: 55pt; color: #00BFFF;"}?

<!--- Research question to validate --->

## Election Forecasting {.smaller}

<!-- Ajouter une source par model --> 

-   Small history
-   Uncertainty and error of election forecasts
-   Four classes of forecasting methods
    1.  Structural models
    2.  Models based on the traditional vote intention question
    3.  Vote expectations, wisdom of the crowd
    4.  Combination of the three
-   These four models do not capture essential information
    -   Potential shifts
    -   Fragile segments

## Bridging this gap: the Relative Confidence Index (RCI)

<!-- Insister ici que c'est "théorique" -->

An innovative range approach to measure vote intention

## How is it Calculated?

<!-- COMMENT C'EST CALCULÉ, copier les slides de l'an passé -->

## What Has Been Done With This Approach?

<!-- Ne pas commencer ton bullet point avec la référence: inverse les deux éléments d’info. Ce qui a été fait d’abord, la référence ensuite. Et assure-toi de bien faire ressortir en quoi cette approche apporte ou répond à de nouvelles questions par rapport aux notes de recherche précédentes. -->

-   Dufresne et al. (2018): Sur le potentiel de croissance du PQ (*On the Potential for Growth of the PQ*)
-   Déry et al. (2022):
-   *Unpublished* Cadieux et al. (2024): On Volatility and Parties' Potential for Growth

{Montrer des graphs intéressants de ces notes de recherche}

<!-- Montrer des graphs intéressants de ces notes de recherche -->

## Theoretical Benefits of Such Measure

-   More suitable to multiparty systems
-   Adding layer of choices → reduction of prediction error
-   More nuance to deal with undecided voters
-   Alleviate uncertainty associated with attitude/behaviour discrepancies
-   Makes a difference between unreachable and reachable electors → [***potential for growth***]{style="font-size: 40pt; color: #00BFFF;"}
-   Makes a difference between a solid and a fragile voter → [***vote solidity***]{style="font-size: 40pt; color: #00BFFF;"}

## Validity at the Individual Level

<!--- What does it mean to be a 3? A -2? A 6? Mettre les probabilités prédites sur l'intention de vote binaire --->

{What does it mean to be a 3? A -2? A 6? Mettre les probabilités prédites sur l'intention de vote binaire}

## Descriptive: RCI Distribution by Party

{Distribution de l'IRC des partis prov et féd}

# Data and Context

## Case Study

-   Quebec Provincial Election, 2022
- CAQ won 89 ridings, majority of seats
- Today's projections, one year later: PQ close to a majority, CAQ **19**

{Montrer le graphique des sièges par parti}
{Expliquer rapidement les 5 partis sur l'axe gauche-droite et leur aspect historique}

- Could we have predicted this {montée} of the PQ?

## Datasets {.smaller}

::: columns
::: {.column width="50%"}
Potential for growth

-   Surveys
    -   Monthly surveys taken from January 2022 to August 2022 (n = 9,135)
    -   (in discussion to obtain Vote Compass' datasets)
-   2021 Canadian Census data (by provincial riding)
:::

::: {.column width="50%"}
Electoral swings

-   2022 Electoral results
-   Qc125.com December 2023 projections
:::
:::

# Methodology

## Estimating the RCI at the Riding-Level

<!-- Why at the riding level? Because electoral results are only at the riding-level -->

-   Step 1: compute regression models to predict the RCI using survey data
-   Step 2: predict those models on riding-level census data
-   Step 3: aggregate the RCI and its uncertainty using segments' weights in the riding

## Step 1: Compute Regression Models to Predict the RCI Using Survey Data

<!-- Il faut trouver une façon de bien expliquer ici -->

-   Vote solidity: `lm(rci ~ age * langue * region * male)` but only for a party's current electoral base
-   Potential for growth: `lm(rci ~ age * langue * region * male)` but only for respondents who do not currently vote for the party
-   Vote intention: `multinom(party ~ age * langue * granular + male)`

## Step 2: Predict Those Models on Riding-Level Census Data

<!-- Avoir tableau/graph exemple pour une circonscription où on voit le poids des répondants, leur prédiction, marge d'erreur etc. -->

## Step 3: Aggregate the RCI and Its Uncertainty Using Segments' Weights in the Riding

<!-- Partir de step 2 et agrégér, trouver une façon que ça soit bien visualisé -->

## Output

{Faire un graphique où on ordonne les ridings pour la CAQ avec les 3 modèles (potgrowth vote solidity et vote intent) sur le graph}

{Faire un graphique qui résume pour une circonscription avec les 5 partis ou pour 2-3 segments dans une circonscription}

<!-- Faire un graphique où on ordonne les ridings pour la CAQ exemple avec les 3 modèles sur le graph -->

<!-- Faire un graphique qui résume pas pire pour une circonscription avec les 5 partis ou pour 2-3 segments dans une circonscription -->

# Results: Can it Improve the Forecasting of Electoral Swings?

## Descriptive Graphs : Distribution of Potential for Growth of Ridings by Party

## Descriptive Graphs : Distribution of Vote Solidity of Ridings by Party

## Descriptive Graphs: Correlation Between Potential for Growth and Actual Qc125 Projections

## Descriptive Graphs: Parties' Electoral Gains Since 2022

<!-- Ici on voit que le PQ a full gagné et la CAQ a full perdu -->

## Using a Traditional Measure: 2022 Vote Shares
{Graphique Vote solidity CAQ VS 2022 Vote Shares}

<!-- From this graph, impossible to explain the montée of the PQ -->

## Using the RCI
{Graphique Vote solidity CAQ VS Potential for growth}
<!-- From this graph, PQ in good position in ridings CAQ won.-->
<!-- Needs a catalyst!!! -->

## Other Potential Future Swings?

<!-- Checker PCQ-CAQ, QS-PLQ, QS-PQ -->

# Article Contributions

-   Empirical results to validate the concept of potential for growth
-   Broadening the recognition of the concept in the field
-   Explore basic and simplified operationalisations
-   Opening the door to more complex operationalisations

# Discussion & Next Steps

## The End of the Line?

### Weak Signal, Yet Still Worth Exploring

-   Preliminary weak findings: caution against premature dismissal of the concept
-   Solid theoretical foundation, derived from logical intuitions
-   Only a handful of operationalisations have been explored as of yet
    -   Broad range of research possibilities

## Improving its Conceptualization

-   Catalysts
    -   Electoral campaign
    -   Salient events
    -   Parties' efforts to reach segments
-   Position of parties and respondents on salient issues
    -   Parties' room to maneuver
-   Political sophistication

## Operationalisation of the Concepts

-   Challenge: need to start with simplistic measures before going into more complicated operationalisations
-   Catalysts

## More Case Studies

- 2021 Canadian Federal Election
- 2024 (?) Canadian Federal Election

## Improving the Models

-   Adding independent variables (income, education, etc.)
    -   Need more data points to add independent variables → VPL (Vote Compass)
    -   (For the synthetic post-stratification table)
-   Testing other types of models
    -   Random forest
    -   Gradient boosting

## Survey Experiments: Better Validation at the Individual Level

-   Panel before and after election to follow the variation across the same individuals
- Survey experiments to test potential framing effects

## The ***Real*** End of the Line {.smaller}

<!-- faire un lien avec mon mémoire -->

**Theoretically valid quantitative indicators of:**

-   The propensity of an individual or group to support a political party, given targeted efforts towards them.
-   The fragility of segments within a party's current electoral base
-   The room to maneuver of parties
    -   Optimal positions on salient issues
    -   Segments to target
-   The estimable number of seats that is possibly reachable by a party if an election campaign would be launched today

<!-- Montrer un exemple du end game avec des données simulées -->
